# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/gigaset/mt6763-common/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/gigaset/mt6763-common

PRODUCT_COPY_FILES += \
    vendor/gigaset/GS290-unified/proprietary/vendor/bin/charon:$(TARGET_COPY_OUT_VENDOR)/bin/charon \
    vendor/gigaset/GS290-unified/proprietary/vendor/bin/libccu_ov168854cell_mipi_raw.dm:$(TARGET_COPY_OUT_VENDOR)/bin/libccu_ov168854cell_mipi_raw.dm \
    vendor/gigaset/GS290-unified/proprietary/vendor/bin/libccu_ov168854cell_mipi_raw.pm:$(TARGET_COPY_OUT_VENDOR)/bin/libccu_ov168854cell_mipi_raw.pm \
    vendor/gigaset/GS290-unified/proprietary/vendor/bin/libccu_ov16885_mipi_raw.dm:$(TARGET_COPY_OUT_VENDOR)/bin/libccu_ov16885_mipi_raw.dm \
    vendor/gigaset/GS290-unified/proprietary/vendor/bin/libccu_ov16885_mipi_raw.pm:$(TARGET_COPY_OUT_VENDOR)/bin/libccu_ov16885_mipi_raw.pm \
    vendor/gigaset/GS290-unified/proprietary/vendor/bin/libccu_s5k3p9_mipi_raw.dm:$(TARGET_COPY_OUT_VENDOR)/bin/libccu_s5k3p9_mipi_raw.dm \
    vendor/gigaset/GS290-unified/proprietary/vendor/bin/libccu_s5k3p9_mipi_raw.pm:$(TARGET_COPY_OUT_VENDOR)/bin/libccu_s5k3p9_mipi_raw.pm \
    vendor/gigaset/GS290-unified/proprietary/vendor/bin/starter:$(TARGET_COPY_OUT_VENDOR)/bin/starter \
    vendor/gigaset/GS290-unified/proprietary/vendor/bin/stroke:$(TARGET_COPY_OUT_VENDOR)/bin/stroke \
    vendor/gigaset/GS290-unified/proprietary/vendor/data/misc/ProjectConfig.mk:$(TARGET_COPY_OUT_VENDOR)/data/misc/ProjectConfig.mk \
    vendor/gigaset/GS290-unified/proprietary/vendor/etc/.tp/thermal.conf:$(TARGET_COPY_OUT_VENDOR)/etc/.tp/thermal.conf \
    vendor/gigaset/GS290-unified/proprietary/vendor/etc/audio_param/AudioParamOptions.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/AudioParamOptions.xml \
    vendor/gigaset/GS290-unified/proprietary/vendor/etc/audio_param/AudioParamVersionInfo.txt:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/AudioParamVersionInfo.txt \
    vendor/gigaset/GS290-unified/proprietary/vendor/etc/audio_param/BtInfo_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/BtInfo_AudioParam.xml \
    vendor/gigaset/GS290-unified/proprietary/vendor/etc/audio_param/HpImpedance_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/HpImpedance_AudioParam.xml \
    vendor/gigaset/GS290-unified/proprietary/vendor/etc/audio_param/PlaybackACF_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackACF_AudioParam.xml \
    vendor/gigaset/GS290-unified/proprietary/vendor/etc/audio_param/PlaybackDRC_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackDRC_AudioParam.xml \
    vendor/gigaset/GS290-unified/proprietary/vendor/etc/audio_param/RecordVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordVol_AudioParam.xml \
    vendor/gigaset/GS290-unified/proprietary/vendor/etc/audio_param/Record_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Record_AudioParam.xml \
    vendor/gigaset/GS290-unified/proprietary/vendor/etc/audio_param/SpeechDMNR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechDMNR_AudioParam.xml \
    vendor/gigaset/GS290-unified/proprietary/vendor/etc/audio_param/SpeechUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechUI_AudioParam.xml \
    vendor/gigaset/GS290-unified/proprietary/vendor/etc/audio_param/SpeechVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechVol_AudioParam.xml \
    vendor/gigaset/GS290-unified/proprietary/vendor/etc/audio_param/Speech_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Speech_AudioParam.xml \
    vendor/gigaset/GS290-unified/proprietary/vendor/etc/audio_param/VOW_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VOW_AudioParam.xml \
    vendor/gigaset/GS290-unified/proprietary/vendor/etc/audio_param/VoIPVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPVol_AudioParam.xml \
    vendor/gigaset/GS290-unified/proprietary/vendor/etc/audio_param/VoIPv2DMNR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2DMNR_AudioParam.xml \
    vendor/gigaset/GS290-unified/proprietary/vendor/etc/audio_param/VoIPv2General_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2General_AudioParam.xml \
    vendor/gigaset/GS290-unified/proprietary/vendor/etc/audio_param/VoIPv2UI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2UI_AudioParam.xml \
    vendor/gigaset/GS290-unified/proprietary/vendor/etc/audio_param/VoIPv2_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2_AudioParam.xml \
    vendor/gigaset/GS290-unified/proprietary/vendor/etc/aurisys_param/Speech_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/aurisys_param/Speech_AudioParam.xml \
    vendor/gigaset/GS290-unified/proprietary/vendor/etc/init/init.md_apps.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.md_apps.rc \
    vendor/gigaset/GS290-unified/proprietary/vendor/lib/hw/audio.primary.mt6763.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/audio.primary.mt6763.so \
    vendor/gigaset/GS290-unified/proprietary/vendor/lib/hw/kmsetkey.default.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/kmsetkey.default.so \
    vendor/gigaset/GS290-unified/proprietary/vendor/lib/hw/kmsetkey.mt6763.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/kmsetkey.mt6763.so \
    vendor/gigaset/GS290-unified/proprietary/vendor/lib/hw/vendor.mediatek.hardware.pq@2.3-impl.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/vendor.mediatek.hardware.pq@2.3-impl.so \
    vendor/gigaset/GS290-unified/proprietary/vendor/lib/libaal_cust.so:$(TARGET_COPY_OUT_VENDOR)/lib/libaal_cust.so \
    vendor/gigaset/GS290-unified/proprietary/vendor/lib/libaal_mtk.so:$(TARGET_COPY_OUT_VENDOR)/lib/libaal_mtk.so \
    vendor/gigaset/GS290-unified/proprietary/vendor/lib/libaalservice.so:$(TARGET_COPY_OUT_VENDOR)/lib/libaalservice.so \
    vendor/gigaset/GS290-unified/proprietary/vendor/lib/libcameracustom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcameracustom.so \
    vendor/gigaset/GS290-unified/proprietary/vendor/lib/libcharon-ss.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcharon-ss.so \
    vendor/gigaset/GS290-unified/proprietary/vendor/lib/libcrypto-ss.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcrypto-ss.so \
    vendor/gigaset/GS290-unified/proprietary/vendor/lib/libcurl-ss.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcurl-ss.so \
    vendor/gigaset/GS290-unified/proprietary/vendor/lib/libhydra.so:$(TARGET_COPY_OUT_VENDOR)/lib/libhydra.so \
    vendor/gigaset/GS290-unified/proprietary/vendor/lib/libmtkcam.logicalmodule.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmtkcam.logicalmodule.so \
    vendor/gigaset/GS290-unified/proprietary/vendor/lib/libmtkcam_metastore.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmtkcam_metastore.so \
    vendor/gigaset/GS290-unified/proprietary/vendor/lib/libsimaka.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsimaka.so \
    vendor/gigaset/GS290-unified/proprietary/vendor/lib/libssl-ss.so:$(TARGET_COPY_OUT_VENDOR)/lib/libssl-ss.so \
    vendor/gigaset/GS290-unified/proprietary/vendor/lib/libstrongswan.so:$(TARGET_COPY_OUT_VENDOR)/lib/libstrongswan.so \
    vendor/gigaset/GS290-unified/proprietary/vendor/lib64/hw/audio.primary.mt6763.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/audio.primary.mt6763.so \
    vendor/gigaset/GS290-unified/proprietary/vendor/lib64/hw/fingerprint.mt6763.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/fingerprint.mt6763.so \
    vendor/gigaset/GS290-unified/proprietary/vendor/lib64/hw/kmsetkey.default.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/kmsetkey.default.so \
    vendor/gigaset/GS290-unified/proprietary/vendor/lib64/hw/kmsetkey.mt6763.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/kmsetkey.mt6763.so \
    vendor/gigaset/GS290-unified/proprietary/vendor/lib64/hw/sensors.mt6763.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/sensors.mt6763.so \
    vendor/gigaset/GS290-unified/proprietary/vendor/lib64/hw/vendor.mediatek.hardware.pq@2.3-impl.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/vendor.mediatek.hardware.pq@2.3-impl.so \
    vendor/gigaset/GS290-unified/proprietary/vendor/lib64/libaal_cust.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libaal_cust.so \
    vendor/gigaset/GS290-unified/proprietary/vendor/lib64/libaal_mtk.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libaal_mtk.so \
    vendor/gigaset/GS290-unified/proprietary/vendor/lib64/libaalservice.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libaalservice.so \
    vendor/gigaset/GS290-unified/proprietary/vendor/lib64/libcameracustom.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcameracustom.so \
    vendor/gigaset/GS290-unified/proprietary/vendor/lib64/libcharon-ss.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcharon-ss.so \
    vendor/gigaset/GS290-unified/proprietary/vendor/lib64/libcrypto-ss.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcrypto-ss.so \
    vendor/gigaset/GS290-unified/proprietary/vendor/lib64/libcurl-ss.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcurl-ss.so \
    vendor/gigaset/GS290-unified/proprietary/vendor/lib64/libhydra.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libhydra.so \
    vendor/gigaset/GS290-unified/proprietary/vendor/lib64/libmtkcam.logicalmodule.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmtkcam.logicalmodule.so \
    vendor/gigaset/GS290-unified/proprietary/vendor/lib64/libmtkcam_hwnode.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmtkcam_hwnode.so \
    vendor/gigaset/GS290-unified/proprietary/vendor/lib64/libmtkcam_metastore.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmtkcam_metastore.so \
    vendor/gigaset/GS290-unified/proprietary/vendor/lib64/libsimaka.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libsimaka.so \
    vendor/gigaset/GS290-unified/proprietary/vendor/lib64/libssl-ss.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libssl-ss.so \
    vendor/gigaset/GS290-unified/proprietary/vendor/lib64/libstrongswan.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libstrongswan.so \
    vendor/gigaset/GS290-unified/proprietary/vendor/thh/ta/04190000000000000000000000000000.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/04190000000000000000000000000000.ta
