# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/gigaset/mt6763-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter GS290 GX290 yggdrasil yggdrasilx,$(TARGET_DEVICE)),)

endif
